### ISSUE TITLE
Consider a private repo

### ISSUE THREAD

**Issue by ngoossens** [marlanperumal/csgo-scripts#1]
It might be nice to make the repo private for just those that have access to the server.

**Comment by marlanperumal** [comment]
Any reason we wouldn't want to leave it public? We shouldn't be storing any secrets in the repo and we could add in an appropriate license :)

**Comment by hrudham** [comment]
I'm OK with leaving this public too. Who knows, maybe someone else will get some use out of these?

**Comment by ngoossens** [comment]
Sure, just need to make sure we handle secrets appropriately :)
