### ISSUE TITLE
Sync with repo

### ISSUE THREAD

**Issue by ngoossens** [marlanperumal/csgo-scripts#7]
Write a script to automatically sync the server configuration with this repo.

**Comment by marlanperumal** [comment]
This seems to cover updating the server https://developer.valvesoftware.com/wiki/SteamCMD#Automating_SteamCMD

Then it would be a matter of setting a CRON job with a post-merge hook - don't know what the equivalent under windows is

**Comment by ngoossens** [comment]
Currently management is handled using https://windowsgsm.com/ and it does a daily restart.

I would suggest we keep a `secrets.cfg` on the server that contains the private config and then just `exec` that from the `server.cfg`. That way we can just run a scheduled task that does a pull on the repo and copies the files.

`server_commands.txt` is taken from the `serverparam` property in the `WindowsGSM.cfg` file (https://docs.windowsgsm.com/getting-started/configuration) so that would require some merging code if we wanted that to be updated automatically. I think we could skip that for v1 though.

**Comment by marlanperumal** [comment]
Ok yeah - I'd been looking at this https://linuxgsm.com/lgsm/csgoserver/#gettingstarted so assumedly that's just the windows version

**Comment by ngoossens** [comment]
Add an hourly task that just copies `botprofile.db`, `cp.cfg` and `server.cfg` to the correct locations. We can expand on that if required.
